const CART_ACTION_TYPES = {
	IS_CART_OPEN: "IS_CART_OPEN",
	ADD_CART_ITEM: "ADD_CART_ITEM",
	REMOVE_CART_ITEM: "REMOVE_CART_ITEM",
	REMOVE_CART_PRODUCT: "REMOVE_CART_PRODUCT"
};

export default CART_ACTION_TYPES;
